version: '3.5'

volumes:
  vscode-server:
  dotlocal:

services:

  importer-init:
    image: indigoiam/voms-importer
    volumes:
      - vscode-server:/home/test/.vscode-server
      - dotlocal:/home/test/.local
    command: sudo chown -R test:test /home/test/.vscode-server /home/test/.local

  importer:
    image: indigoiam/voms-importer

    depends_on:
      - importer-init

    environment:
      - TZ=Europe/Rome
      - BEARER_TOKEN
      - REQUESTS_CA_BUNDLE=/etc/pki/tls/cert.pem
      - X509_USER_PROXY=/tmp/x509up_u501

    volumes:
      - vscode-server:/home/test/.vscode-server
      - dotlocal:/home/test/.local
      - $HOME/git/indigo-aai-tutorial:/home/test/indigo-aai-tutorial
      - $HOME/grid-security:/etc/grid-security/certificates
      - $HOME/ca-bundle:/etc/pki
      - $HOME/vomsdir:/etc/grid-security/vomsdir:ro
      - $HOME/vomses:/etc/vomses
      - $HOME/.globus:/home/test/.globus:ro
      - $HOME/.config/oidc-agent:/home/test/.config/oidc-agent:ro
      - ..:/home/test/workspace:cached

    entrypoint: /tini -- sleep infinity

    extra_hosts:
      - "iam.local.io: 192.168.65.2"
