name: build docker image

on:
  push:
    branches:
      - master
jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: indigoiam/voms-importer:latest
          context: ./docker
          file: ./docker/Dockerfile
          push: false

      - name: Push docker image
        run: docker push indigoiam/voms-importer:latest
