name: build docker image

on: [push, pull_request]

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: indigoiam/voms-importer
          tags: |
            type=sha
            type=semver,pattern={{raw}}
            type=ref,event=branch

      - name: Copy script to docker dir
        run: cp vomsimporter.py docker

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          context: ./docker
          file: ./docker/Dockerfile
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
